[nara]
api_key="4xAb9IEf1568AYb4eaRUY8f0admbxZIF4QvZYLjT"

[datadotworld]
token="eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJweXRob246YXJhZ2FvY2IiLCJpc3MiOiJjbGllbnQ6cHl0aG9uOmFnZW50OmFyYWdhb2NiOjplNTU2ODlmMy0yMWUyLTQ1MGEtOTJmZC1hMGFhYmE4NjViODciLCJpYXQiOjE3MzQwNjIxMzQsInJvbGUiOlsidXNlcl9hcGlfYWRtaW4iLCJ1c2VyX2FwaV9yZWFkIiwidXNlcl9hcGlfd3JpdGUiXSwiZ2VuZXJhbC1wdXJwb3NlIjp0cnVlLCJzYW1sIjp7fX0.iuDURaiISvXQfa40lt3RRrcxeiMvkku2VL6TDv3yAE5vKOQSrLVbY3kgjoCBoxRKaLiDofKGssKLnCK4eP38kQ"